MvcKutuphane/Controllers/YazarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKutuphane.Models.Entity;
namespace MvcKutuphane.Controllers
{
    public class YazarController : Controller
    {
        // GET: Yazar
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();
        public ActionResult Index()
        {
            var degerler = db.TBLyazar.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult YazarEkle()
        {
            return View();
        }


        public ActionResult YazarEkle(TBLyazar p)
        {
            db.TBLyazar.Add(p);
            db.SaveChanges();
            return View();
        }
        public ActionResult YazarSil(int id)
        {
            var yazar = db.TBLyazar.Find(id);
            db.TBLyazar.Remove(yazar);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult YazarGetir(int id)
        {
            var yzr = db.TBLyazar.Find(id);
            return View("YazarGetir", yzr);
        }
        public ActionResult YazarGuncelle(TBLyazar p)
        {
            var yzr = db.TBLyazar.Find(p.ID);
            yzr.AD = p.AD;
            yzr.SOYAD = p.SOYAD;
            yzr.DETAY = p.DETAY;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcKutuphane/Views/Yazar/Index.cshtml
@using MvcKutuphane.Models.Entity
@model List<TBLyazar>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Yazarlar</h2>

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>AD</th>
        <th>SOYAD</th>
        <th>DETAY</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach(var y in Model)
            {
                <tr>
                    <td>@y.ID</td>
                    <td>@y.AD</td>
                    <td>@y.SOYAD</td>
                    <td>@y.DETAY</td>
                    <td><a href="/Yazar/YazarSil/@y.ID" class="btn btn-danger">Sil</a></td>>               
                    <td><a href="/Yazar/YazarGetir/@y.ID" class="btn btn-success">Güncelle</a></td>
                </tr>
            }
</table>
<a class="btn btn-primary" href="/Yazar/YazarEkle/">Yeni Yazar Ekle</a>

MvcKutuphane/Views/Yazar/YazarEkle.cshtml
@model MvcKutuphane.Models.Entity.TBLyazar
@{
    ViewBag.Title = "YazarEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<form class="form-group" method="post">

    <div style="margin-top:15px">
        <label>Yazar adı</label>
        @Html.TextBoxFor(y => y.AD, new { @class = "form-control" })

    </div>
    <div style="margin-top:15px">
        <label>Yazar Soyadı</label>
        @Html.TextBoxFor(y => y.SOYAD, new { @class = "form-control" })

    </div>
    <div style="margin-top:15px">
        <label>Detay</label>
        @Html.TextAreaFor(y => y.DETAY, new { @class = "form-control" })

    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info">Yazar Ekle</button>
    </div>
</form>

MvcKutuphane/Views/Yazar/YazarGetir.cshtml
@model MvcKutuphane.Models.Entity.TBLyazar
@{
    ViewBag.Title = "YazarGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}
@using(Html.BeginForm("YazarGüncelle","Yazar",FormMethod.Post))
            {
                <div class="form-group">
                    <div style="margin-bottom:15px">
                        <label>Yazar ID</label>
                        @Html.TextBoxFor(y => y.ID, new { @class = "form-control" })
                    </div>
                    <div style="margin-bottom:15px">
                        <label>Yazar Adı</label>
                        @Html.TextBoxFor(y => y.AD, new { @class = "form-control" })
                    </div>
                    <div style="margin-bottom:15px">
                        <label>Yazar Soyad</label>
                        @Html.TextBoxFor(y => y.SOYAD, new { @class = "form-control" })
                    </div>
                    <div style="margin-bottom:15px">
                        <label>Yazar Detay Bilgi</label>
                        @Html.TextAreaFor(y => y.DETAY, new { @class = "form-control" })
                    </div>
                    <button class="btn btn-warning">Yazar Bilgilerini güncelle</button>
                </div>
            }