MvcKutuphane/Controllers/KitapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKutuphane.Models.Entity;
namespace MvcKutuphane.Controllers
{
    public class KitapController : Controller
    {
        // GET: Kitap
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();
        public ActionResult Index(string p)
        {
            var kitaplar = from k in db.TBLKİTAP select k;
            if(string.IsNullOrEmpty(p))
            {
                kitaplar = kitaplar.Where(m => m.AD.Contains(p));
            }
            //var kitaplar = db.TBLKİTAP.ToList();
            return View(kitaplar.ToList());
        }
        [HttpGet]
        public ActionResult KitapEkle()
        {
            List<SelectListItem> deger1=(from i in db.TBLKategori.ToList()
                                         select new SelectListItem
                                         {
                                             Text=i.ADI,
                                             Value=i.ID.ToString(),
                                         }).ToList();
            ViewBag.dgr1 = deger1;
            List<SelectListItem> deger2= (from i in db.TBLyazar.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.AD +' '+  i.SOYAD,
                                               Value = i.ID.ToString(),
                                           }).ToList();
            ViewBag.dgr2 = deger2;

            return View();
        }
        [HttpPost]
        public ActionResult KitapEkle(TBLKİTAP p)
        {
            var ktg = db.TBLKategori.Where(k => k.ID == p.TBLKategori.ID).FirstOrDefault();
            var yzr=db.TBLyazar.Where(y=>y.ID==p.TBLyazar.ID).FirstOrDefault();
            p.TBLKategori= ktg;
            p.TBLyazar= yzr;
            db.TBLKİTAP.Add(p);
            db.SaveChanges();
            return RedirectToAction("Index");
            
        }
        public ActionResult KitapSil(int id)
        {
            var kitap = db.TBLKİTAP.Find(id);
            db.TBLKİTAP.Remove(kitap);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KitapGetir(int id)
        {
            var ktp = db.TBLKİTAP.Find(id);
            List<SelectListItem> deger1 = (from i in db.TBLKategori.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.ADI,
                                               Value = i.ID.ToString(),
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            List<SelectListItem> deger2 = (from i in db.TBLyazar.ToList()
                                          select new SelectListItem
                                          {
                                              Text = i.AD + ' ' + i.SOYAD,
                                              Value = i.ID.ToString(),
                                          }).ToList();
            ViewBag.dgr2 = deger2;
            return View("KitapGetir", ktp);
        }
        public ActionResult KitapGüncelle(TBLKİTAP p)
        {
            var kitap = db.TBLKİTAP.Find(p.ID);
            kitap.AD = p.AD;
            kitap.BASIMYIL=p.BASIMYIL;
            kitap.SAYFA = p.SAYFA;
            kitap.YAYINEVİ = p.YAYINEVİ;
            var ktg=db.TBLKategori.Where(k=>k.ID==p.TBLKategori.ID).FirstOrDefault();
            var yzr=db.TBLyazar.Where(y=>y.ID==p.TBLyazar.ID).FirstOrDefault();
            kitap.KATEGORİ = ktg.ID;
            kitap.YAZAR=yzr.ID;
            db.SaveChanges();
            return RedirectToAction("Index");

        }
    }

}

MvcKutuphane/Views/Kitap/Index.cshtml
@using MvcKutuphane.Models.Entity
@model List<TBLKİTAP>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Kitap Sayfası</h2>
@using (Html.BeginForm("Index", "Kitap", FormMethod.Get))
{

    <div style="margin-bottom:15px; margin-top:15px;">
       <b>Arancak Kitap Adını Giriniz...</b>@Html.TextBox("p")
        <input type="submit" value="Ara" />
    </div>
}

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Kitap Adı</th>
        <th>Kitap Yazarı</th>
        <th>Kategorisi</th>
        <th>Basım Yılı</th>
        <th>Yayın Evi</th>
        <th>Sayfa</th>
        <th>Durum</th>
        <th>Sil</th>
        <th>Güncelle</th>
    </tr>
    @foreach (var k in Model)
    {
        <tr>
            <td>@k.ID</td>
            <td>@k.AD</td>
            <td>@k.TBLyazar.AD @k.TBLyazar.SOYAD</td>
            <td>@k.TBLKategori.ADI </td>
            <td>@k.BASIMYIL</td>
            <td>@k.YAYINEVİ</td>
            <td>@k.SAYFA</td>>
            <td>@k.DURUMU</td>
            <td>
                <a href="/Kitap/KİtapSil/@k.ID" class="btn btn-danger">Sil</a>
            </td>
            <td><a href="/Kitap/KİtapGetir/@k.ID" class="btn btn-success">Güncelle</a></td>


        </tr>
    }

</table>
<a href="/Kitap/KitapEkle" class="btn btn-primary">Yeni Kitap Ekle</a>

MvcKutuphane/Views/Kitap/KitapEkle.cshtml
@model MvcKutuphane.Models.Entity.TBLKİTAP
@{
    ViewBag.Title = "KitapEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<form class="form-group" method="post">

    <div style="margin-top:15px">
        <label>Kitap adı</label>
        @Html.TextBoxFor(k => k.AD, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Kitap Kategori</label>
        @Html.DropDownListFor(k=>k.TBLKategori.ID,(List<SelectListItem>)ViewBag.dgr1,
       new {@class= "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Yazar</label>
        @Html.DropDownListFor(k => k.TBLyazar.ID, (List<SelectListItem>)ViewBag.dgr2,
new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Basım Yılı</label>
        @Html.TextBoxFor(k => k.BASIMYIL, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Yayın Evi</label>
        @Html.TextBoxFor(k => k.YAYINEVİ, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Sayfa Sayısı</label>
        @Html.TextBoxFor(k => k.SAYFA, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info">Kitap Ekle</button>
    </div>
</form>

MvcKutuphane/Views/Kitap/KitapGetir.cshtml
@model MvcKutuphane.Models.Entity.TBLKİTAP
@{
    {
        ViewBag.Title = "KitapGetir";
        Layout = "~/Views/Shared/Layout.cshtml";
    }
        }
    <h2>KitapGetir</h2>
     
    @using (Html.BeginForm("KitapGüncelle", "Kitap", FormMethod.Post))
    {
        <div class="form-group">
            <div style="margin-bottom:15px">
                <label>Kitap ID</label>
                @Html.TextBoxFor(k => k.ID, new { @class = "form-control" })
            </div>
            <div style="margin-bottom:15px">
                <label>Kitap Adı</label>
                @Html.TextBoxFor(k => k.AD, new { @class = "form-control" })
            </div>
            <div style="margin-bottom:15px">
                <label>Kategori</label>
                 @Html.DropDownListFor(k => k.TBLKategori.ID, (List<SelectListItem>)ViewBag.dgr1,
                 new { @class = "form-control" })
            </div>
            <div style="margin-bottom:15px">
                <label>Yazarı</label>
                @Html.DropDownListFor(k => k.TBLyazar.ID, (List<SelectListItem>)ViewBag.dgr2,
new { @class = "form-control" })
            </div>
            <div style="margin-bottom:15px">
                <label>Basım Yılı</label>
                @Html.TextBoxFor(k => k.BASIMYIL, new { @class = "form-control" })
            </div>
            <div style="margin-bottom:15px">
                <label>Yayın Evi</label>
                @Html.TextBoxFor(k => k.YAYINEVİ, new { @class = "form-control" })
            </div>
            <div style="margin-bottom:15px">
                <label>Sayfa Sayısı</label>
                @Html.TextBoxFor(k => k.SAYFA, new { @class = "form-control" })
            </div>
           

            <button class="btn btn-warning">Kitap Bilgilerini güncelle</button>
        </div>
    }