MvcKutuphane/Controllers/PersonelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKutuphane.Models.Entity;
namespace MvcKutuphane.Controllers
{
    public class PersonelController : Controller
    {

        // GET: Personel
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();
        public ActionResult Index()
        {
            var degerler = db.TBLPERSONEL.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult PersonelEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult PersonelEkle(TBLPERSONEL p)
        {
            if(!ModelState.IsValid)
            {
                return View("PersonelEkle");
            }
            db.TBLPERSONEL.Add(p);
            db.SaveChanges();
            return View();
        }
        public ActionResult PersonelSil(int id)
        {
            var person = db.TBLPERSONEL.Find(id);
            db.TBLPERSONEL.Remove(person);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult PersonelGetir(int id)
        {
            var prs = db.TBLPERSONEL.Find(id);
            return View("PersonelGetir", prs);
        }
        public ActionResult PersonelGüncelle(TBLPERSONEL p)
        {
            var prs = db.TBLPERSONEL.Find(p.ID);
            prs.PERSONEL = p.PERSONEL;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcKutuphane/Views/Personel/Index.cshtml
@using MvcKutuphane.Models.Entity
@model List<TBLPERSONEL>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Personeller</h2>

<table class="table table-bordered">
    <tr>
        <th>PERSONEL ID</th>
        <th>PERSONEL ADI</th>
        <th>SİL</th>
        <th>GÜNCELLE</th>
    </tr>
    @foreach (var prs in Model)
    {
        <tr>
            <td>@prs.ID</td>
            <td>@prs.PERSONEL</td>
            <td><a href="/personel/personelSil/@prs.ID" class="btn btn-danger">Sil</a></td>
            <td><a href="/personel/personelGetir/@prs.ID" class="btn btn-success">Güncelle</a></td>
        </tr>
    }

</table>
<a href="/Personel/PersonelEkle/" class="btn btn-primary"> Yeni personel Ekle</a>

MvcKutuphane/Views/Personel/PersonelEkle.cshtml
@model MvcKutuphane.Models.Entity.TBLPERSONEL

@{
    ViewBag.Title = "PersonelEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<form class="form-group" method="post">

    <div style="margin-top:15px">
        <label>Personel Adı</label>
        @*<input type="text" class="form-control" name="PERSONEL" />*@
        @Html.TextBoxFor(x=>x.PERSONEL,new {@class="form-control" })
        @Html.ValidationMessageFor(x => x.PERSONEL, "", new {@style="color:red"})
    </div>
    <div style="margin-top:15px">
        <button class="btn btn-info" id="Btn1">Personel Ekle</button>
    </div>
</form>

MvcKutuphane/Views/Personel/PersonelGetir.cshtml
@model MvcKutuphane.Models.Entity.TBLPERSONEL
@{
    ViewBag.Title = "PersonelGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}



@using (Html.BeginForm("PersonelGüncelle", "Personel", FormMethod.Post))
{
    <div style="margin-bottom:15px"></div>

    <div class="form-group">
        @Html.LabelFor(k => k.ID)
        @Html.TextBoxFor(K => K.ID, new { @class = "form-control" })
        <br />
        @*@Html.LabelFor(k => k.PERSONEL)*@
        <label>Personel Adı</label>
        @Html.TextBoxFor(K => K.PERSONEL, new { @class = "form-control" })
    </div>
    <div>
        <button class="btn btn-warning">Güncelle</button>
    </div>
}